# Generated by Django 4.0.6 on 2022-07-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
