# Generated by Django 4.0.6 on 2022-08-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0009_alter_post_categories_alter_post_image'),
        ('blogposts', '0009_alter_post_categories_alter_post_image 2'),
    ]

    operations = [
    ]
