# Generated by Django 4.0.6 on 2022-08-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0009_alter_post_categories_alter_post_image 3'),
        ('blogposts', '0009_alter_post_categories_alter_post_image 4'),
        ('blogposts', '0009_alter_post_categories_alter_post_image 5'),
        ('blogposts', '0010_merge_20220806_2043 2'),
        ('blogposts', '0010_merge_20220806_2043 3'),
        ('blogposts', '0010_merge_20220806_2043 4'),
        ('blogposts', '0011_alter_post_image'),
        ('blogposts', '0011_alter_post_image 2'),
    ]

    operations = [
    ]
