# Generated by Django 4.0.6 on 2022-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0012_merge_20220811_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='uploaded_images/bmo.png', null=True, upload_to='uploaded_images/'),
        ),
    ]
